const Data = {
    productItems: [{
            id: 1,
            discount: 50,
            cover: "/public/images/phone/iphone-15.jpg",
            description: "iPhone 15",
            name: "iPhone 15",
            price: 22990000,
        },
        {
            id: 2,
            discount: 40,
            cover: "/public/images/phone/iphone-15-pro.jpg",
            description: "iPhone 15 Pro",
            name: "iPhone 15 Pro",
            price: 27990000,
        },
        {
            id: 3,
            discount: 40,
            cover: "/public/images/phone/iphone-15-pro-max.jpg",
            description: "iPhone 15 Pro Max",
            name: "iPhone 15 Pro Max",
            price: 33990000,
        },
        {
            id: 4,
            discount: 40,
            cover: "/public/images/phone/iphone-15-plus.jpg",
            description: "iPhone 15 Plus",
            name: "iPhone 15 Plus",
            price: 25990000,
        },
        {
            id: 5,
            discount: 50,
            cover: "/public/images/phone/iPhone-14-thumb.jpg",
            description: "iPhone 14",
            name: "iPhone 14",
            price: 19190000,
        },
        {
            id: 6,
            discount: 50,
            cover: "/public/images/phone/iphone-14-pro.jpg",
            description: "iPhone 14 Pro",
            name: "iPhone 14 Pro",
            price: 24190000,
        },
        {
            id: 7,
            discount: 50,
            cover: "/public/images/phone/iphone-14-pro-max.jpg",
            description: "iPhone 14 Pro Max",
            name: "iPhone 14 Pro Max",
            price: 26490000,
        },
        {
            id: 8,
            discount: 50,
            cover: "/public/images/phone/iPhone-14-plus.jpg",
            description: "iPhone 14 Plus",
            name: "iPhone 14 Plus",
            price: 21790000,
        },
        {
            id: 9,
            discount: 50,
            cover: "/public/images/phone/iphone-13.jpg",
            description: "iPhone 13",
            name: "iPhone 13",
            price: 21790000,
        },
        {
            id: 10,
            discount: 50,
            cover: "/public/images/phone/iPhone-12.jpg",
            description: "iPhone 12",
            name: "iPhone 12",
            price: 21790000,
        },
        {
            id: 11,
            discount: 50,
            cover: "/public/images/phone/iPhone-11.jpg",
            description: "iPhone 11",
            name: "iPhone 11",
            price: 21790000,
        },
        {
            id: 12,
            discount: 50,
            cover: "/public/images/phone/oppo-a57.jpeg",
            description: "OPPO A57",
            name: "OPPO A57",
            price: 21790000,
        },
        {
            id: 13,
            discount: 50,
            cover: "/public/images/phone/oppo-find-n2-flip.jpg",
            description: "OPPO Find N2 Flip",
            name: "OPPO Find N2 Flip",
            price: 21790000,
        },
        {
            id: 14,
            discount: 50,
            cover: "/public/images/phone/oppo-reno10-pro-plus.jpg",
            description: "OPPO Reno10 Pro+",
            name: "OPPO Reno10 Pro+",
            price: 21790000,
        },
        {
            id: 15,
            discount: 50,
            cover: "/public/images/phone/oppo-reno10-pro.jpg",
            description: "OPPO Reno10 Pro",
            name: "OPPO Reno10 Pro",
            price: 21790000,
        },
    ],
};
export default Data;